theme: jekyll-theme-minimal
title: Identifying topics/pages to be included in Indian Language Wikipedia
# description: Identifying topics from news to add to Hindi Wikipedia
# logo: [Location of the logo]
